### ISSUE TITLE
URL Encoding issues causes some queries not to return

### ISSUE THREAD

**Issue by FM1337** [Krognol/go-wolfram#1]
Due to the following line: `url := "https://api.wolframalpha.com/v2/query?" + params.Encode()`

Queries like 1ft to in would fail to return

reason being: when you do params.Encode() 1ft to in becomes 1ft+to+in which isn't accepted by the API correctly. Plus you're placing spaces with %20, which means it becomes 1ft%2520to%2520in

I've fixed this by doing 
`url := "https://api.wolframalpha.com/v2/query?appid=" + c.AppID + "&input=" + query`

As I'm not sure if you even support this repo anymore and I needed a fix for my application, I've gone ahead and just made the changes and included this application as a module for my application which if I read the license correctly it is allowed.

If you do happen to apply the fixes, I would be more than happy to remove it as a module and just import like normal.

Thanks!

**Comment by FM1337** [comment]
Actually investigating further, 1ft+to+in works fine, but for some reason encoding breaks it

**Comment by Krognol** [comment]
I'm actually aware of this problem and I could've sworn I pushed a fix for it. In any case, I will probably update this entire thing some time soon™ since they've updated their API.
